image:https://circleci.com/gh/aerogear/ios-showcase-template.svg?style=svg["CircleCI", link="https://circleci.com/gh/aerogear/ios-showcase-template"]
image:https://img.shields.io/badge/Swift%20Version-4.0-green.svg[]

= Aerogear Services iOS Showcase Application Template

A Native iOS Application that demonstrates features of the Aerogear iOS SDK.

== Features
- OpenID Connect Authentication
- Single Sign-on
- Mobile Access Control
- Client Cert Authentication
- Certificate Pinning
- Secure Data Storage
- Buffer Overflow Protections
- Device Trust Checks (Jailbreak, latest OS etc)
- iOS Snapshot Caching Protection
- Binary Protections (Automatic Reference Counting, ASLR, Stack Smashing Protection)
- 2FA with OTP (via Keycloak)
- Authentication Brute Force Detection (via Keycloak)
- Account Lockout Policies (via Keycloak)
- Authentication/Access Control Auditing & Logging (via Keycloak)
- Authenticated Calls to Protected Endpoints (via Keycloak)
- Push notifications with UPS server

== Work with Self-signed Certificate

The easiest way to support self-signed certificate is to install the CA certificate that is used to sign the certificate onto the device/simulator.

1. Get the CA certificate of the server. You can use this command:
+
[source, bash]
----
openssl s_client -showcerts -connect host:port
---- 
+
It will print out the full certificate chain of the server and you should save the content of the root certificate into a PEM file.

2. Install the CA certificate onto the device.
+
To install onto an iOS simulator, you can simply drag & drop the certificate file over it.
+
To install on an actual device, you can use a file sharing service or send the certificate file as an email attachment.

3. Ensure the newly installed CA certificate is trusted. 
+
On the device/simulator, go to `Settings -> General -> About -> Certificate Trust Settings` and enable full trust for the certificate.