version: 2
jobs:
  build:
    working_directory: ~/aerogear/showcase
    macos:
      xcode: "9.3.0"
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Install lint
          command: brew install swiftlint
      - run:
          name: Check style using swiftlint
          command: swiftlint
      - run:
          name: Fetch dev dependencies
          command: git clone git@github.com:aerogear/aerogear-ios-sdk.git sdk
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      # Install CocoaPods
      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            LOCAL_DIR=./sdk pod install

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 7
            SCAN_SCHEME: ios-showcase-template

      - run:
          name: Push to Kryptowire
          command: ./scripts/pushToKryptowire.sh $KRYPTOWIRE_API_KEY

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: ./test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
